name: Build, Push, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: ‚öôÔ∏è Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: ‚öôÔ∏è Checkout code
        uses: actions/checkout@v3

      - name: üõü Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name:  Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build-and-push  # ensures it waits for the first job to finish

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ../home/goinnovior

            echo "Stopping and removing old containers..."
            docker compose --profile prod down --remove-orphans

            echo "Removing old images..."
            docker compose rm -f

            docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.PROJECT_NAME }}:latest

            echo "Pulling latest images..."
            docker compose pull

            echo "Starting new containers..."
            docker compose --profile prod up -d

            echo "Waiting for containers remove unused images"
            docker image prune -f

            echo "Deployment completed successfully."